### ISSUE TITLE
LDAPAuthenticator.java 168 NullPointerException

### ISSUE THREAD

**Issue by ghost** [instaclustr/cassandra-ldap#5]
Hi, 

I have followed the steps under "Configuration". 
When starting cassandra, I am getting the below NPE (apache-cassandra-3.11.3 $ bin/cassandra -f). 

Any idea? Not sure when/where `private static ClientState state;` is initialized.

Best regards, 
Bernhard

`Exception (java.lang.NullPointerException) encountered during startup: null
java.lang.NullPointerException
	at com.instaclustr.cassandra.ldap.LDAPAuthenticator.validateConfiguration(LDAPAuthenticator.java:168)
	at org.apache.cassandra.auth.AuthConfig.applyAuth(AuthConfig.java:108)
	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:143)
	at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:647)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:582)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:691)
ERROR [main] 2018-11-09 15:52:24,888 CassandraDaemon.java:708 - Exception encountered during startup
java.lang.NullPointerException: null
	at com.instaclustr.cassandra.ldap.LDAPAuthenticator.validateConfiguration(LDAPAuthenticator.java:168) ~[cassandra-ldap-3.11.2.jar:na]
	at org.apache.cassandra.auth.AuthConfig.applyAuth(AuthConfig.java:108) ~[apache-cassandra-3.11.3.jar:3.11.3]
	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:143) ~[apache-cassandra-3.11.3.jar:3.11.3]
	at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:647) [apache-cassandra-3.11.3.jar:3.11.3]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:582) [apache-cassandra-3.11.3.jar:3.11.3]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:691) [apache-cassandra-3.11.3.jar:3.11.3]`

**Comment by migscabral** [comment]
**+1** on this. Would like to understand as well how `ClientState state` gets instantiated.

**Comment by smiklosovic** [comment]
Hi @bkk2918 and @migscabral 

please use the current branch 3.11. We will get rid of master soon as there is a bug which prevents you from running this successfully.

**Comment by smiklosovic** [comment]
I have tested the current branch 3.11 which goes against Cassandra 3.11.4 with OpenLDAP server (setup is in the README) and I was able to connect without problems. Please let me know if you have any problems.
