### ISSUE TITLE
Should rebuild cassandra-ldap plugin for cassandra verion >= 4.1.6

### ISSUE THREAD

**Issue by NikLoginov** [instaclustr/cassandra-ldap#52]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
4.1.7
### What version of Cassandra LDAP are you using?
v4.1.0-1.0.0

### What did you do?
Upgrade cassandra from 4.1.5 to 4.1.7

### What did you expect to see?
Working ldap plugin.

### What did you see instead?
```
ERROR [main] 2024-10-09 12:23:56,704+0300 CassandraDaemon.java:900 - Exception encountered during startup
java.lang.NoSuchMethodError: 'org.apache.cassandra.transport.messages.ResultMessage$Rows org.apache.cassandra.cql3.statements.SelectStatement.execute(org.apache.cassandra.service.QueryState, org.apache.cassandra.cql3.QueryOptions, long)'
        at com.instaclustr.cassandra.ldap.auth.Cassandra41SystemAuthRoles.getRole(Cassandra41SystemAuthRoles.java:156)
        at org.apache.cassandra.auth.LDAPCassandraRoleManager.canLogin(LDAPCassandraRoleManager.java:169)
        at org.apache.cassandra.auth.LDAPCassandraRoleManager.lambda$setup$0(LDAPCassandraRoleManager.java:95)
        at org.apache.cassandra.auth.LDAPCassandraRoleManager.setup(LDAPCassandraRoleManager.java:141)
        at org.apache.cassandra.service.StorageService.doAuthSetup(StorageService.java:1359)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:444)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:744)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:878)
DEBUG [StorageServiceShutdownHook] 2024-10-09 12:23:56,709+0300 StorageService.java:1921 - DRAINING: starting drain process
```
---
### Reason of the error
https://github.com/apache/cassandra/blob/cassandra-4.1.7/NEWS.txt#L75

> Upgrading
> ---------
>     - Note that the QueryHandler interface has been changed to accomodate
>       improved management of pending requests; any custom implementations
>       (using the cassandra.custom_query_handler_class system property) will
>       need to be recompiled.  For further details, see CASSANDRA-19534.

**Comment by iAlex97** [comment]
We have also experienced this issues, a quick and dirty fix would be to use the version which targets cassandra 5.0.0. The signature of the interface is virtually the same.

**Comment by smiklosovic** [comment]
should be fixed by now
